#!/bin/sh

case "$1" in
    start)
        sudo -u sculptor /usr/bin/sculptor agent start
        ;;
    stop)
        sudo -u sculptor /usr/bin/sculptor agent stop
        ;;
    status)
        sudo -u sculptor /usr/bin/sculptor agent status
        ;;
    restart|reload|force-reload)
        sudo -u sculptor /usr/bin/sculptor agent stop
        sudo -u sculptor /usr/bin/sculptor agent start
        ;;
esac
